# Generated by Django 5.2.16 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
