# Generated by Django 5.2.16 on 2026-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('failed', 'فشل')], default='pending', max_length=20),
        ),
    ]
