# Generated by Django 5.2.16 on 2026-07-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_coupon_code_order_discount_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount off, in QAR.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cart subtotal must reach this amount before the code can be applied. Leave blank for no minimum.', max_digits=10, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Total times this code can be used across all customers. Leave blank for unlimited.', null=True)),
                ('max_redemptions_per_customer', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
