# Generated by Django 5.2.16 on 2026-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='قيمة الخصم الثابتة، بالجنيه السوداني (ج.س).', max_digits=10),
        ),
    ]
