# Generated by Django 6.0.7 on 2026-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label - not shown to customers.', max_length=150)),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('cart', 'Cart'), ('checkout', 'Checkout')], max_length=20)),
                ('image', models.ImageField(upload_to='banners/')),
                ('target_url', models.URLField(help_text='External link the banner opens (in a new tab) when clicked.')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first when more than one banner is active for the same placement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['placement', 'order', '-created_at'],
            },
        ),
    ]
