# Generated by Django 6.0.7 on 2026-07-23 09:41

from django.db import migrations, models


def remap_homepage_placement(apps, schema_editor):
    Banner = apps.get_model('ads', 'Banner')
    Banner.objects.filter(placement='homepage').update(placement='homepage_1')


def unmap_homepage_placement(apps, schema_editor):
    Banner = apps.get_model('ads', 'Banner')
    Banner.objects.filter(placement__in=['homepage_1', 'homepage_2']).update(placement='homepage')


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('homepage_1', 'Homepage - banner 1'), ('homepage_2', 'Homepage - banner 2'), ('cart', 'Cart'), ('checkout', 'Checkout')], max_length=20),
        ),
        migrations.RunPython(remap_homepage_placement, unmap_homepage_placement),
    ]
