# Generated by Django 5.2.16 on 2026-07-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_banner_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
