# Generated by Django 5.2.16 on 2026-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_banner_clicks_banner_impressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('homepage_1', 'الصفحة الرئيسية - بانر 1'), ('homepage_2', 'الصفحة الرئيسية - بانر 2'), ('cart', 'السلة'), ('checkout', 'إتمام الطلب')], max_length=20),
        ),
    ]
