# Generated by Django 6.0.7 on 2026-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ads_enabled',
            field=models.BooleanField(default=True, help_text='Show advertising banners on the homepage, cart, and checkout pages.'),
        ),
    ]
