# Generated by Django 6.0.7 on 2026-07-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_waitlistsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitlistSignup',
        ),
    ]
