# Generated by Django 5.2.16 on 2026-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_visitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(default='بنك الخرطوم', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_note',
            field=models.CharField(blank=True, default='حوّل المبلغ عبر تطبيق بنكك (Bankak) إلى الحساب أعلاه، ثم ارفع صورة إيصال التحويل.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_estimate',
            field=models.CharField(default='٢-٤ أسابيع', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='coming_soon_message',
            field=models.TextField(blank=True, default='نعمل على وضع اللمسات الأخيرة على شيء رائع. تابعونا قريبًا.'),
        ),
    ]
