# Generated by Django 5.2.16 on 2026-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_sitesettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='usd_to_sdg_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='كم جنيهًا سودانيًا يساوي الدولار الواحد الآن. حدّثه كل ما تغيّر السعر.', max_digits=10),
        ),
    ]
