# Generated by Django 5.2.16 on 2026-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sitesettings_usd_to_sdg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='usd_to_sdg_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='كم جنيهًا سودانيًا يساوي الدولار الواحد الآن. حدّثه كل ما تغيّر السعر.', max_digits=10),
        ),
    ]
