# Generated by Django 5.2.16 on 2026-08-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_sitesettings_usd_to_sdg_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='bank_transfer_note',
            field=models.CharField(blank=True, default='حوّل المبلغ عبر تطبيق  (Bankak) إلى الحساب أعلاه، ثم ارفع صورة إيصال التحويل.', max_length=255),
        ),
        migrations.CreateModel(
            name='MarketInsightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'جارٍ التحليل'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_insight_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market insight report',
                'ordering': ['-created_at'],
            },
        ),
    ]
