# Generated by Django 6.0.7 on 2026-07-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=20),
        ),
    ]
