# Generated by Django 5.2.16 on 2026-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'موظف'), ('manager', 'مدير')], default='staff', max_length=20),
        ),
    ]
