# Generated by Django 5.2.16 on 2026-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
