# Generated by Django 5.2.16 on 2026-07-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_code_order_discount_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_carrier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
