# Generated by Django 5.2.16 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_tracking_carrier_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warranty_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
