# Generated by Django 5.2.16 on 2026-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_backfill_orderitem_condition_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='condition',
            field=models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('changed_mind', 'غيّرت رأيي'), ('wrong_item', 'استلمت منتجًا خاطئًا'), ('no_longer_needed', 'لم أعد بحاجته'), ('damaged', 'وصل المنتج تالفًا'), ('defective', 'المنتج به عيب'), ('other', 'سبب آخر')], max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='resolution_requested',
            field=models.CharField(choices=[('refund', 'استرداد المبلغ'), ('exchange', 'استبدال بمنتج آخر'), ('replacement', 'استبدال بنفس المنتج')], max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20),
        ),
    ]
