# Generated by Django 5.2.16 on 2026-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status_alter_orderitem_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
