# Generated by Django 5.2.16 on 2026-08-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
