# Generated by Django 6.0.7 on 2026-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty period in months. Leave blank if this product carries no warranty.', null=True),
        ),
    ]
