# Generated by Django 5.2.16 on 2026-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon name, e.g. "shopping-bag" for the fa-shopping-bag icon. Takes priority over the tile image when set.', max_length=50),
        ),
    ]
