# Generated by Django 5.2.16 on 2026-07-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon name, e.g. "shopping-bag" for the fa-shopping-bag icon.', max_length=50),
        ),
    ]
