# Generated by Django 5.2.16 on 2026-08-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_category_image_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty period in months. Leave blank if this product carries no warranty. For used products, warranty is typically short (up to 1 month / ~30 days).', null=True),
        ),
    ]
