# Generated by Django 5.2.16 on 2026-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_warranty_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
    ]
