# Generated by Django 5.2.16 on 2026-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_condition_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='بالدولار الأمريكي (USD)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='بالدولار الأمريكي (USD). اتركه فارغًا لاستخدام سعر المنتج.', max_digits=10, null=True),
        ),
    ]
